name: OWASP Dependency-Check Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  dependency-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12' 

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt 
          
      - name: Run OWASP Dependency-Check
        uses: dependency-check/Dependency-Check_Action@v4 # Use the latest version
        with:
          project: 'app' # Name your project
          path: '.' # Scan the current directory
          format: 'SARIF,HTML' # Generate SARIF and HTML reports
