name: Security Scan and Tests

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master ]

jobs:
  security-scan:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests
      run: |
        pytest tests/ -v

    - name: Run Bandit SAST
      run: |
        bandit -r app/ -f html -o bandit_report.html || true

    - name: Run Safety SCA
      run: |
        safety check --json --output safety_report.json || true

    - name: Run OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'blog-api'
        path: '.'
        format: 'HTML'
        out: 'reports'

    - name: Upload Bandit report
      uses: actions/upload-artifact@v4
      with:
        name: bandit-report
        path: bandit_report.html

    - name: Upload Safety report
      uses: actions/upload-artifact@v4
      with:
        name: safety-report
        path: safety_report.json

    - name: Upload Dependency Check report
      uses: actions/upload-artifact@v4
      with:
        name: dependency-check-reports
        path: reports/

  code-quality:
    runs-on: ubuntu-latest
    needs: security-scan
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Test with pytest
      run: |
        pytest tests/ --junitxml=pytest-results.xml

    - name: Upload pytest results
      uses: actions/upload-artifact@v4
      with:
        name: pytest-results
        path: pytest-results.xml
      if: always()
